avoid decorate result for json payload
ideacrew/event_source pull request #90
Opened 2023-07-11 21:07 UTC by ymhari

2023-07-12 17:16 UTC, kristinmerbach submitted a review, later dismissed

2023-07-13 14:33 UTC, TreyE requested changes

2023-07-13 14:37 UTC, kristinmerbach commented on lib/event_source/protocols/http/soap/payload_header_middleware.rb
> +
The options are the server level, and we have both json and xml requests going to the same server, so it needs to be on the request level.

2023-07-13 15:18 UTC, kristinmerbach commented on lib/event_source/protocols/http/soap/payload_header_middleware.rb
> +
@TreyE Hari updated to instead check for the presence of the authorization header which will be set for all the ones that need to skip the soap auth

2023-07-17 14:44 UTC, TreyE approved these changes

2023-07-17 14:45 UTC, kristinmerbach approved these changes

2023-07-17 14:46 UTC, merged